# PlantVillage 38-class label map
# Index → raw class name (as used during training)

CLASS_LABELS = [
    "Apple___Apple_scab",
    "Apple___Black_rot",
    "Apple___Cedar_apple_rust",
    "Apple___healthy",
    "Blueberry___healthy",
    "Cherry_(including_sour)___Powdery_mildew",
    "Cherry_(including_sour)___healthy",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot",
    "Corn_(maize)___Common_rust_",
    "Corn_(maize)___Northern_Leaf_Blight",
    "Corn_(maize)___healthy",
    "Grape___Black_rot",
    "Grape___Esca_(Black_Measles)",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)",
    "Grape___healthy",
    "Orange___Haunglongbing_(Citrus_greening)",
    "Peach___Bacterial_spot",
    "Peach___healthy",
    "Pepper,_bell___Bacterial_spot",
    "Pepper,_bell___healthy",
    "Potato___Early_blight",
    "Potato___Late_blight",
    "Potato___healthy",
    "Raspberry___healthy",
    "Soybean___healthy",
    "Squash___Powdery_mildew",
    "Strawberry___Leaf_scorch",
    "Strawberry___healthy",
    "Tomato___Bacterial_spot",
    "Tomato___Early_blight",
    "Tomato___Late_blight",
    "Tomato___Leaf_Mold",
    "Tomato___Septoria_leaf_spot",
    "Tomato___Spider_mites Two-spotted_spider_mite",
    "Tomato___Target_Spot",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus",
    "Tomato___Tomato_mosaic_virus",
    "Tomato___healthy",
]

# Maps raw label → (plantName, cleanDiseaseName, isHealthy)
LABEL_METADATA = {
    "Apple___Apple_scab":                                   ("Apple",       "Apple Scab",                    False),
    "Apple___Black_rot":                                    ("Apple",       "Black Rot",                     False),
    "Apple___Cedar_apple_rust":                             ("Apple",       "Cedar Apple Rust",              False),
    "Apple___healthy":                                      ("Apple",       "Healthy",                       True),
    "Blueberry___healthy":                                  ("Blueberry",   "Healthy",                       True),
    "Cherry_(including_sour)___Powdery_mildew":             ("Cherry",      "Powdery Mildew",                False),
    "Cherry_(including_sour)___healthy":                    ("Cherry",      "Healthy",                       True),
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot":   ("Corn",        "Gray Leaf Spot",                False),
    "Corn_(maize)___Common_rust_":                          ("Corn",        "Common Rust",                   False),
    "Corn_(maize)___Northern_Leaf_Blight":                  ("Corn",        "Northern Leaf Blight",          False),
    "Corn_(maize)___healthy":                               ("Corn",        "Healthy",                       True),
    "Grape___Black_rot":                                    ("Grape",       "Black Rot",                     False),
    "Grape___Esca_(Black_Measles)":                         ("Grape",       "Esca (Black Measles)",          False),
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)":           ("Grape",       "Leaf Blight",                   False),
    "Grape___healthy":                                      ("Grape",       "Healthy",                       True),
    "Orange___Haunglongbing_(Citrus_greening)":             ("Orange",      "Citrus Greening (HLB)",         False),
    "Peach___Bacterial_spot":                               ("Peach",       "Bacterial Spot",                False),
    "Peach___healthy":                                      ("Peach",       "Healthy",                       True),
    "Pepper,_bell___Bacterial_spot":                        ("Bell Pepper", "Bacterial Spot",                False),
    "Pepper,_bell___healthy":                               ("Bell Pepper", "Healthy",                       True),
    "Potato___Early_blight":                                ("Potato",      "Early Blight",                  False),
    "Potato___Late_blight":                                 ("Potato",      "Late Blight",                   False),
    "Potato___healthy":                                     ("Potato",      "Healthy",                       True),
    "Raspberry___healthy":                                  ("Raspberry",   "Healthy",                       True),
    "Soybean___healthy":                                    ("Soybean",     "Healthy",                       True),
    "Squash___Powdery_mildew":                              ("Squash",      "Powdery Mildew",                False),
    "Strawberry___Leaf_scorch":                             ("Strawberry",  "Leaf Scorch",                   False),
    "Strawberry___healthy":                                 ("Strawberry",  "Healthy",                       True),
    "Tomato___Bacterial_spot":                              ("Tomato",      "Bacterial Spot",                False),
    "Tomato___Early_blight":                                ("Tomato",      "Early Blight",                  False),
    "Tomato___Late_blight":                                 ("Tomato",      "Late Blight",                   False),
    "Tomato___Leaf_Mold":                                   ("Tomato",      "Leaf Mold",                     False),
    "Tomato___Septoria_leaf_spot":                          ("Tomato",      "Septoria Leaf Spot",            False),
    "Tomato___Spider_mites Two-spotted_spider_mite":        ("Tomato",      "Spider Mites",                  False),
    "Tomato___Target_Spot":                                 ("Tomato",      "Target Spot",                   False),
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus":               ("Tomato",      "Yellow Leaf Curl Virus",        False),
    "Tomato___Tomato_mosaic_virus":                         ("Tomato",      "Mosaic Virus",                  False),
    "Tomato___healthy":                                     ("Tomato",      "Healthy",                       True),
}
