export interface DiseaseInfo {
  displayName: string;
  isHealthy: boolean;
  cause: string;
  spread: string;
  treatmentType: string;
  prevention: string[];
  urgency: "none" | "low" | "medium" | "high";
}

export const DISEASE_KNOWLEDGE: Record<string, DiseaseInfo> = {
  "Apple Scab": {
    displayName: "Apple Scab",
    isHealthy: false,
    cause: "Caused by the fungus Venturia inaequalis, which overwinters in fallen infected leaves.",
    spread: "Spreads via wind-dispersed ascospores and conidia during wet spring conditions when temperatures are 55–75°F.",
    treatmentType: "Fungicide (captan or myclobutanil)",
    prevention: [
      "Rake and destroy fallen leaves in autumn to reduce overwintering spores",
      "Apply protective fungicide sprays from bud break through early summer",
      "Plant scab-resistant apple varieties when possible",
    ],
    urgency: "medium",
  },
  "Apple with Black Rot": {
    displayName: "Black Rot",
    isHealthy: false,
    cause: "Caused by the fungus Botryosphaeria obtusa, which persists in dead wood and mummified fruit.",
    spread: "Spreads through rain splash and wind dispersal of spores from infected bark cankers and mummified fruit.",
    treatmentType: "Fungicide (captan-based) + prune infected wood",
    prevention: [
      "Remove and destroy mummified fruit and dead wood from trees",
      "Apply fungicide sprays during the growing season starting at pink bud stage",
      "Maintain good tree vigor through proper fertilization and irrigation",
    ],
    urgency: "high",
  },
  "Cedar Apple Rust": {
    displayName: "Cedar Apple Rust",
    isHealthy: false,
    cause: "Caused by the fungus Gymnosporangium juniperi-virginianae, which requires both apple and cedar/juniper hosts to complete its life cycle.",
    spread: "Spreads via wind-dispersed spores released from orange gelatinous galls on cedar trees during wet spring weather.",
    treatmentType: "Fungicide (myclobutanil or mancozeb)",
    prevention: [
      "Remove nearby juniper and cedar trees if possible, as they are alternate hosts",
      "Apply fungicide at pink bud stage and continue through petal fall",
      "Plant rust-resistant apple cultivars in areas where cedar trees are common",
    ],
    urgency: "medium",
  },
  "Healthy Apple": {
    displayName: "Healthy Apple",
    isHealthy: true,
    cause: "No disease detected.",
    spread: "N/A",
    treatmentType: "No treatment needed",
    prevention: [
      "Maintain current care routine",
      "Ensure proper watering and sunlight",
    ],
    urgency: "none",
  },
  "Healthy Blueberry Plant": {
    displayName: "Healthy Blueberry",
    isHealthy: true,
    cause: "No disease detected.",
    spread: "N/A",
    treatmentType: "No treatment needed",
    prevention: [
      "Maintain current care routine",
      "Ensure proper watering and sunlight",
    ],
    urgency: "none",
  },
  "Cherry with Powdery Mildew": {
    displayName: "Powdery Mildew",
    isHealthy: false,
    cause: "Caused by the fungus Podosphaera clandestina, which colonizes leaf surfaces and young shoots.",
    spread: "Spreads rapidly through airborne conidia, especially in warm dry days followed by cool humid nights.",
    treatmentType: "Fungicide (sulfur-based or potassium bicarbonate)",
    prevention: [
      "Prune to improve air circulation within the canopy",
      "Avoid excessive nitrogen fertilization which promotes susceptible succulent growth",
      "Apply preventive sulfur sprays before disease onset in spring",
    ],
    urgency: "medium",
  },
  "Healthy Cherry Plant": {
    displayName: "Healthy Cherry",
    isHealthy: true,
    cause: "No disease detected.",
    spread: "N/A",
    treatmentType: "No treatment needed",
    prevention: [
      "Maintain current care routine",
      "Ensure proper watering and sunlight",
    ],
    urgency: "none",
  },
  "Corn (Maize) with Cercospora and Gray Leaf Spot": {
    displayName: "Gray Leaf Spot",
    isHealthy: false,
    cause: "Caused by the fungus Cercospora zeae-maydis, which overwinters in infected crop debris.",
    spread: "Spreads through wind and rain splash of conidia, favored by warm temperatures (75–95°F) and high humidity.",
    treatmentType: "Fungicide (strobilurin or triazole-based)",
    prevention: [
      "Rotate corn with non-host crops such as soybeans to reduce inoculum",
      "Till crop residue after harvest to accelerate decomposition of infected debris",
      "Plant resistant hybrid varieties in fields with history of the disease",
    ],
    urgency: "high",
  },
  "Corn (Maize) with Common Rust": {
    displayName: "Common Rust",
    isHealthy: false,
    cause: "Caused by the obligate fungal pathogen Puccinia sorghi, which requires living host tissue to survive.",
    spread: "Spreads via wind-dispersed urediniospores that can travel hundreds of miles from infected fields.",
    treatmentType: "Fungicide (triazole or strobilurin)",
    prevention: [
      "Plant resistant corn hybrids, which are the most effective management strategy",
      "Apply fungicide at early infection stages before disease severity exceeds 5%",
      "Scout fields regularly during silking and tasseling when plants are most vulnerable",
    ],
    urgency: "medium",
  },
  "Corn (Maize) with Northern Leaf Blight": {
    displayName: "Northern Leaf Blight",
    isHealthy: false,
    cause: "Caused by the fungus Exserohilum turcicum (formerly Helminthosporium turcicum), surviving in infected debris.",
    spread: "Spreads through wind and splashing rain carrying conidia, favored by moderate temperatures (65–80°F) and prolonged leaf wetness.",
    treatmentType: "Fungicide (strobilurin + triazole mixture)",
    prevention: [
      "Use hybrids with partial resistance (Ht gene) to reduce severity",
      "Rotate away from corn for at least one year to reduce soil-borne inoculum",
      "Apply fungicide at tasseling if lesions appear on the third leaf below the ear or higher",
    ],
    urgency: "high",
  },
  "Healthy Corn (Maize) Plant": {
    displayName: "Healthy Corn",
    isHealthy: true,
    cause: "No disease detected.",
    spread: "N/A",
    treatmentType: "No treatment needed",
    prevention: [
      "Maintain current care routine",
      "Ensure proper watering and sunlight",
    ],
    urgency: "none",
  },
  "Grape with Black Rot": {
    displayName: "Black Rot",
    isHealthy: false,
    cause: "Caused by the fungus Guignardia bidwellii, which overwinters in mummified berries and infected canes.",
    spread: "Spreads via rain-splashed ascospores and conidia from mummified fruit, most active during warm wet periods.",
    treatmentType: "Fungicide (mancozeb or myclobutanil)",
    prevention: [
      "Remove all mummified berries and infected canes during dormant pruning",
      "Apply fungicide from bud swell through berry set, the most critical infection window",
      "Ensure good canopy airflow through shoot positioning and leaf removal",
    ],
    urgency: "high",
  },
  "Grape with Esca (Black Measles)": {
    displayName: "Esca (Black Measles)",
    isHealthy: false,
    cause: "Caused by a complex of wood-rotting fungi including Phaeomoniella chlamydospora and Phaeoacremonium species.",
    spread: "Spreads through pruning wounds and is introduced into vineyards via infected planting material.",
    treatmentType: "Remove infected wood; no curative treatment available",
    prevention: [
      "Make pruning cuts during dry weather and seal large wounds with fungicidal paint",
      "Source certified virus- and pathogen-free planting material",
      "Delay pruning until late in the dormant season to minimize wound exposure time",
    ],
    urgency: "high",
  },
  "Grape with Isariopsis Leaf Spot": {
    displayName: "Isariopsis Leaf Spot",
    isHealthy: false,
    cause: "Caused by the fungus Pseudocercospora vitis (syn. Isariopsis clavispora), favoring warm humid conditions.",
    spread: "Spreads by wind and rain dispersal of conidia from infected leaves, particularly in late summer.",
    treatmentType: "Fungicide (copper-based or mancozeb)",
    prevention: [
      "Maintain good air circulation through canopy management and proper vine spacing",
      "Apply preventive copper fungicide sprays when conditions favor disease development",
      "Remove and destroy fallen infected leaves to reduce overwintering inoculum",
    ],
    urgency: "low",
  },
  "Healthy Grape Plant": {
    displayName: "Healthy Grape",
    isHealthy: true,
    cause: "No disease detected.",
    spread: "N/A",
    treatmentType: "No treatment needed",
    prevention: [
      "Maintain current care routine",
      "Ensure proper watering and sunlight",
    ],
    urgency: "none",
  },
  "Orange with Citrus Greening": {
    displayName: "Citrus Greening (HLB)",
    isHealthy: false,
    cause: "Caused by the bacterium Candidatus Liberibacter asiaticus, transmitted by the Asian citrus psyllid insect.",
    spread: "Spreads through feeding by infected Asian citrus psyllid (Diaphorina citri) or via infected budwood grafting.",
    treatmentType: "No cure; manage psyllid vector with insecticide",
    prevention: [
      "Control Asian citrus psyllid populations with systemic insecticides (imidacloprid)",
      "Use certified disease-free nursery stock and avoid moving budwood from infected areas",
      "Remove and destroy infected trees promptly to reduce the bacterial reservoir in the orchard",
    ],
    urgency: "high",
  },
  "Peach with Bacterial Spot": {
    displayName: "Bacterial Spot",
    isHealthy: false,
    cause: "Caused by the bacterium Xanthomonas arboricola pv. pruni, which overwinters in infected buds and twigs.",
    spread: "Spreads through rain splash and wind-driven rain dispersing bacteria from cankers onto leaves, fruit, and young shoots.",
    treatmentType: "Copper bactericide sprays",
    prevention: [
      "Apply copper-based bactericides from shuck split through cover sprays",
      "Plant resistant or tolerant peach varieties where available",
      "Avoid overhead irrigation to minimize leaf wetness periods that favor infection",
    ],
    urgency: "medium",
  },
  "Healthy Peach Plant": {
    displayName: "Healthy Peach",
    isHealthy: true,
    cause: "No disease detected.",
    spread: "N/A",
    treatmentType: "No treatment needed",
    prevention: [
      "Maintain current care routine",
      "Ensure proper watering and sunlight",
    ],
    urgency: "none",
  },
  "Bell Pepper with Bacterial Spot": {
    displayName: "Bacterial Spot",
    isHealthy: false,
    cause: "Caused by Xanthomonas campestris pv. vesicatoria bacteria, which can survive in soil and plant debris.",
    spread: "Spreads through splashing rain, contaminated tools, and infected seed, thriving in warm (75–86°F) wet weather.",
    treatmentType: "Copper bactericide + mancozeb",
    prevention: [
      "Use certified pathogen-free or hot-water-treated seed before planting",
      "Apply copper-based bactericide sprays preventively during warm wet periods",
      "Avoid working in fields when plants are wet to prevent mechanical spread",
    ],
    urgency: "medium",
  },
  "Healthy Bell Pepper Plant": {
    displayName: "Healthy Bell Pepper",
    isHealthy: true,
    cause: "No disease detected.",
    spread: "N/A",
    treatmentType: "No treatment needed",
    prevention: [
      "Maintain current care routine",
      "Ensure proper watering and sunlight",
    ],
    urgency: "none",
  },
  "Potato with Early Blight": {
    displayName: "Early Blight",
    isHealthy: false,
    cause: "Caused by the fungus Alternaria solani, which overwinters in infected plant debris and soil.",
    spread: "Spreads through wind and rain splash of conidia, favored by warm temperatures (75–84°F) and alternating wet and dry periods.",
    treatmentType: "Fungicide (chlorothalonil or mancozeb)",
    prevention: [
      "Rotate potatoes with non-solanaceous crops for at least two years",
      "Apply preventive fungicide sprays starting when plants are under stress or show early symptoms",
      "Maintain adequate soil fertility, especially nitrogen, to reduce plant stress susceptibility",
    ],
    urgency: "medium",
  },
  "Potato with Late Blight": {
    displayName: "Late Blight",
    isHealthy: false,
    cause: "Caused by the oomycete Phytophthora infestans, the same pathogen responsible for the Irish Potato Famine.",
    spread: "Spreads rapidly through wind-dispersed sporangia during cool (50–70°F), wet, and humid conditions.",
    treatmentType: "Fungicide (mancozeb or chlorothalonil); remove infected tissue",
    prevention: [
      "Plant certified disease-free seed potatoes and resistant varieties",
      "Apply preventive fungicides before disease onset, especially during cool wet weather",
      "Destroy volunteer potato plants and cull piles that serve as inoculum sources",
    ],
    urgency: "high",
  },
  "Healthy Potato Plant": {
    displayName: "Healthy Potato",
    isHealthy: true,
    cause: "No disease detected.",
    spread: "N/A",
    treatmentType: "No treatment needed",
    prevention: [
      "Maintain current care routine",
      "Ensure proper watering and sunlight",
    ],
    urgency: "none",
  },
  "Healthy Raspberry Plant": {
    displayName: "Healthy Raspberry",
    isHealthy: true,
    cause: "No disease detected.",
    spread: "N/A",
    treatmentType: "No treatment needed",
    prevention: [
      "Maintain current care routine",
      "Ensure proper watering and sunlight",
    ],
    urgency: "none",
  },
  "Healthy Soybean Plant": {
    displayName: "Healthy Soybean",
    isHealthy: true,
    cause: "No disease detected.",
    spread: "N/A",
    treatmentType: "No treatment needed",
    prevention: [
      "Maintain current care routine",
      "Ensure proper watering and sunlight",
    ],
    urgency: "none",
  },
  "Squash with Powdery Mildew": {
    displayName: "Powdery Mildew",
    isHealthy: false,
    cause: "Caused by the fungus Podosphaera xanthii (formerly Sphaerotheca fuliginea), an obligate parasite of cucurbit plants.",
    spread: "Spreads through airborne conidia that do not require free water for germination, thriving in warm dry conditions with high humidity.",
    treatmentType: "Fungicide (potassium bicarbonate, sulfur, or neem oil)",
    prevention: [
      "Plant resistant squash varieties which are widely available and highly effective",
      "Ensure adequate plant spacing to promote air circulation and reduce humidity",
      "Apply preventive organic sprays (neem oil or potassium bicarbonate) early in the season",
    ],
    urgency: "medium",
  },
  "Strawberry with Leaf Scorch": {
    displayName: "Leaf Scorch",
    isHealthy: false,
    cause: "Caused by the fungus Diplocarpon earlianum, which persists in infected plant debris and mummified tissue.",
    spread: "Spreads by rain-splashed conidia from infected leaves and crowns, most severe in wet cool spring weather.",
    treatmentType: "Fungicide (captan or myclobutanil)",
    prevention: [
      "Remove and destroy old and infected leaves after harvest to reduce inoculum",
      "Apply fungicide preventively at early growth and repeat after heavy rainfall",
      "Use certified disease-free transplants and avoid planting in previously infected beds",
    ],
    urgency: "medium",
  },
  "Healthy Strawberry Plant": {
    displayName: "Healthy Strawberry",
    isHealthy: true,
    cause: "No disease detected.",
    spread: "N/A",
    treatmentType: "No treatment needed",
    prevention: [
      "Maintain current care routine",
      "Ensure proper watering and sunlight",
    ],
    urgency: "none",
  },
  "Tomato with Bacterial Spot": {
    displayName: "Bacterial Spot",
    isHealthy: false,
    cause: "Caused by multiple species of Xanthomonas bacteria (X. euvesicatoria, X. vesicatoria, X. perforans, X. gardneri).",
    spread: "Spreads through splashing rain and irrigation water, contaminated tools, and infected seed during warm wet weather.",
    treatmentType: "Copper bactericide + mancozeb",
    prevention: [
      "Use certified disease-free or hot-water-treated seed",
      "Apply copper-based bactericide sprays preventively when wet weather is forecast",
      "Practice crop rotation and avoid overhead irrigation to limit leaf wetness",
    ],
    urgency: "medium",
  },
  "Tomato with Early Blight": {
    displayName: "Early Blight",
    isHealthy: false,
    cause: "Caused by the fungus Alternaria solani, which persists in soil and infected plant debris between seasons.",
    spread: "Spreads via wind and rain splash of conidia, worsened by warm temperatures (75–84°F) and periods of leaf wetness.",
    treatmentType: "Fungicide (chlorothalonil or mancozeb)",
    prevention: [
      "Rotate tomatoes with non-solanaceous crops for at least two years",
      "Remove lower infected leaves promptly to slow upward spread within the canopy",
      "Apply mulch to reduce soil splash onto lower leaves and maintain consistent irrigation",
    ],
    urgency: "medium",
  },
  "Tomato with Late Blight": {
    displayName: "Late Blight",
    isHealthy: false,
    cause: "Caused by the oomycete Phytophthora infestans, a highly destructive pathogen that can destroy entire fields rapidly.",
    spread: "Spreads through wind-dispersed sporangia during cool (50–70°F), wet, and humid conditions with devastating speed.",
    treatmentType: "Fungicide (mancozeb or chlorothalonil); destroy infected plants",
    prevention: [
      "Apply preventive fungicides before disease onset when cool wet weather is expected",
      "Remove and destroy volunteer tomato and potato plants near fields",
      "Avoid overhead irrigation and ensure good air circulation to reduce humidity",
    ],
    urgency: "high",
  },
  "Tomato with Leaf Mold": {
    displayName: "Leaf Mold",
    isHealthy: false,
    cause: "Caused by the fungus Passalora fulva (formerly Fulvia fulva), which thrives in high humidity greenhouse conditions.",
    spread: "Spreads through airborne conidia, most problematic in enclosed growing environments with poor ventilation.",
    treatmentType: "Fungicide (chlorothalonil or mancozeb); improve ventilation",
    prevention: [
      "Maintain greenhouse humidity below 85% by improving ventilation and heating",
      "Space plants adequately and remove lower leaves to improve airflow",
      "Apply preventive fungicide at the first sign of infection and repeat every 7–10 days",
    ],
    urgency: "medium",
  },
  "Tomato with Septoria Leaf Spot": {
    displayName: "Septoria Leaf Spot",
    isHealthy: false,
    cause: "Caused by the fungus Septoria lycopersici, which overwinters in infected plant debris in the soil.",
    spread: "Spreads through rain splash and infected soil particles hitting lower leaves, progressing upward through the canopy.",
    treatmentType: "Fungicide (chlorothalonil, mancozeb, or copper-based)",
    prevention: [
      "Remove lower infected leaves immediately to prevent upward spread",
      "Mulch around plant bases to prevent soil splash and bury debris",
      "Rotate tomatoes away from solanaceous crops and apply preventive fungicide sprays",
    ],
    urgency: "medium",
  },
  "Tomato with Spider Mites or Two-spotted Spider Mite": {
    displayName: "Spider Mite Damage",
    isHealthy: false,
    cause: "Caused by infestation of the two-spotted spider mite Tetranychus urticae, a common arachnid pest of tomatoes.",
    spread: "Spreads by crawling between plants, through wind, on clothing and tools, and rapidly multiplies in hot dry conditions.",
    treatmentType: "Miticide (abamectin or bifenazate); neem oil for organic control",
    prevention: [
      "Maintain adequate irrigation as water-stressed plants are far more susceptible to mite outbreaks",
      "Introduce or preserve natural predators such as Phytoseiulus persimilis predatory mites",
      "Monitor plants regularly and apply miticide at first sign of stippling before populations explode",
    ],
    urgency: "high",
  },
  "Tomato with Target Spot": {
    displayName: "Target Spot",
    isHealthy: false,
    cause: "Caused by the fungus Corynespora cassiicola, a wide host range pathogen found in tropical and subtropical regions.",
    spread: "Spreads through airborne conidia and splash dispersal, favored by warm temperatures (77°F) and prolonged leaf wetness.",
    treatmentType: "Fungicide (azoxystrobin or chlorothalonil)",
    prevention: [
      "Ensure good air circulation through proper spacing and pruning of lower foliage",
      "Apply preventive fungicide sprays starting at first fruit set and throughout fruiting",
      "Avoid overhead irrigation and water early in the day so foliage dries before nightfall",
    ],
    urgency: "medium",
  },
  "Tomato Yellow Leaf Curl Virus": {
    displayName: "Yellow Leaf Curl Virus",
    isHealthy: false,
    cause: "Caused by Tomato yellow leaf curl virus (TYLCV), a begomovirus transmitted exclusively by the silverleaf whitefly.",
    spread: "Spreads only through the feeding of viruliferous Bemisia tabaci whiteflies; there is no seed or mechanical transmission.",
    treatmentType: "No cure; control whitefly vector with insecticide or reflective mulch",
    prevention: [
      "Control whitefly populations using yellow sticky traps, insecticides, or reflective silver mulch",
      "Use TYLCV-resistant or tolerant tomato varieties where available",
      "Remove and destroy infected plants promptly to reduce the virus reservoir in the field",
    ],
    urgency: "high",
  },
  "Tomato Mosaic Virus": {
    displayName: "Tomato Mosaic Virus",
    isHealthy: false,
    cause: "Caused by Tomato mosaic virus (ToMV), a tobamovirus that is one of the most stable plant viruses known.",
    spread: "Spreads primarily through mechanical contact — contaminated hands, tools, clothing, and infected seed.",
    treatmentType: "No cure; remove infected plants; strict sanitation",
    prevention: [
      "Wash hands thoroughly and disinfect tools with 10% bleach or phosphate detergent between plants",
      "Use certified virus-free seed or hot-water-treated seed before planting",
      "Plant resistant varieties carrying the Tm-2² resistance gene",
    ],
    urgency: "high",
  },
  "Healthy Tomato Plant": {
    displayName: "Healthy Tomato",
    isHealthy: true,
    cause: "No disease detected.",
    spread: "N/A",
    treatmentType: "No treatment needed",
    prevention: [
      "Maintain current care routine",
      "Ensure proper watering and sunlight",
    ],
    urgency: "none",
  },
};

export function getDiseaseInfo(label: string): DiseaseInfo {
  return (
    DISEASE_KNOWLEDGE[label] ?? {
      displayName: label,
      isHealthy: false,
      cause: "Unknown cause",
      spread: "Unknown spread",
      treatmentType: "Consult an agricultural expert",
      prevention: ["Monitor your plant regularly"],
      urgency: "medium",
    }
  );
}
